branch-defaults:
  09_containerization:
    environment: anton123f-card-api-dev
  09_task:
    environment: anton123f-card-api-dev
    group_suffix: null
global:
  application_name: anton123f-card-api
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
